# Generated by Django 5.1.1 on 2024-09-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_content', '0002_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieContent',
            fields=[
                ('screencontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='screen_content.screencontent')),
            ],
            bases=('screen_content.screencontent',),
        ),
        migrations.CreateModel(
            name='TVShowContent',
            fields=[
                ('screencontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='screen_content.screencontent')),
            ],
            bases=('screen_content.screencontent',),
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='screencontent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tvshow',
            options={},
        ),
        migrations.RemoveField(
            model_name='screencontent',
            name='polymorphic_ctype',
        ),
    ]
