# Generated by Django 5.1.1 on 2024-10-07 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_content', '0002_alter_userprofile_user_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='screencontent',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
