# Generated by Django 5.1.1 on 2024-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_content', '0003_moviecontent_tvshowcontent_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screencontent',
            name='genres',
            field=models.ManyToManyField(to='screen_content.genre', verbose_name='genres'),
        ),
    ]
