# Generated by Django 5.1.1 on 2024-09-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_content', '0004_alter_screencontent_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, to='screen_content.screencontent'),
        ),
    ]
