# Generated by Django 5.1.1 on 2024-09-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen_content', '0005_alter_userprofile_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieContent',
        ),
        migrations.DeleteModel(
            name='TVShowContent',
        ),
    ]
